// This file is auto-generated by the sketch schematics. Because I was too lazy to do this in a smart way,
// it just overwrites the file all the time. So be careful when you go editing this yourself if you keep
// using the schematics.

import { SketchRoutes } from '../core';
import { RoutedSketchPageComponent } from '../modules/shared/pages/routed-sketch-page/routed-sketch-page.component';

// Sketch imports
import { hito1 } from 'src/app/sketches/hitomezachi-stitch/hito1.sketch';
import { hito2 } from 'src/app/sketches/hitomezachi-stitch/hito2.sketch';
import { hito3 } from 'src/app/sketches/hitomezachi-stitch/hito3.sketch';
import { hito4 } from 'src/app/sketches/hitomezachi-stitch/hito4.sketch';
import { joyDivision1 } from 'src/app/sketches/joy-division/joy-division-1.sketch';

// sketch routes (sorry it's not pretty :( )
export const SKETCH_ROUTES: SketchRoutes = [
  {
    path: 'hitomezachi-stitch',
    collectionTitle: 'Hitomezachi stitch',
    children: [
      {
        path: 'hito1',
        component: RoutedSketchPageComponent,
        data: hito1,
      },
      {
        path: 'hito2',
        component: RoutedSketchPageComponent,
        data: hito2,
      },
      {
        path: 'hito3',
        component: RoutedSketchPageComponent,
        data: hito3,
      },
      {
        path: 'hito4',
        component: RoutedSketchPageComponent,
        data: hito4,
      },
    ],
  },
  {
    path: 'joy-division',
    collectionTitle: 'Joy division',
    children: [
      {
        path: 'joy-division-1',
        component: RoutedSketchPageComponent,
        data: joyDivision1,
      },
    ],
  },
];
