// This file is auto-generated by the sketch schematics. Because I was too lazy to do this in a smart way,
// it just overwrites the file all the time. So be careful when you go editing this yourself if you keep
// using the schematics.

import { SketchRoutes } from '../core';
import { RoutedSketchPageComponent } from '../modules/shared/pages/routed-sketch-page/routed-sketch-page.component';

// Sketch imports
import { basicTreeSketch } from 'src/app/sketches/basic-tree.sketch';
import { leaf } from 'src/app/sketches/leaf.sketch';
import { randomDiagonalLines } from 'src/app/sketches/random-diagonal-lines.sketch';
import { randomGuassianLines } from 'src/app/sketches/random-guassian-lines.sketch';
import { randomLines } from 'src/app/sketches/random-lines.sketch';
import { bezierFiddle } from 'src/app/sketches/bezier/bezier-fiddle.sketch';
import { bezierFlow1 } from 'src/app/sketches/bezier/bezier-flow-1.sketch';
import { bezierFlow2Interactive } from 'src/app/sketches/bezier/bezier-flow-2-interactive.sketch';
import { bezierFlow2Static } from 'src/app/sketches/bezier/bezier-flow-2-static.sketch';
import { bezierGrid1 } from 'src/app/sketches/bezier/bezier-grid-1.sketch';
import { bezierGrid2 } from 'src/app/sketches/bezier/bezier-grid-2.sketch';
import { bezierGrid3Interactive } from 'src/app/sketches/bezier/bezier-grid-3-interactive.sketch';
import { bezierGrid3Static } from 'src/app/sketches/bezier/bezier-grid-3-static.sketch';
import { flowFieldSketch1 } from 'src/app/sketches/flow-field/flow-field-1.sketch';
import { hito1 } from 'src/app/sketches/hitomezachi-stitch/hito1.sketch';
import { hito2 } from 'src/app/sketches/hitomezachi-stitch/hito2.sketch';
import { hito3 } from 'src/app/sketches/hitomezachi-stitch/hito3.sketch';
import { hito4 } from 'src/app/sketches/hitomezachi-stitch/hito4.sketch';
import { joyDivision1 } from 'src/app/sketches/joy-division/joy-division-1.sketch';

// sketch routes (sorry it's not pretty :( )
export const SKETCH_ROUTES: SketchRoutes = [
  {
    path: 'basic-tree',
    component: RoutedSketchPageComponent,
    data: basicTreeSketch,
  },
  {
    path: 'leaf',
    component: RoutedSketchPageComponent,
    data: leaf,
  },
  {
    path: 'random-diagonal-lines',
    component: RoutedSketchPageComponent,
    data: randomDiagonalLines,
  },
  {
    path: 'random-guassian-lines',
    component: RoutedSketchPageComponent,
    data: randomGuassianLines,
  },
  {
    path: 'random-lines',
    component: RoutedSketchPageComponent,
    data: randomLines,
  },
  {
    path: 'bezier',
    collectionTitle: 'Bezier',
    children: [
      {
        path: 'bezier-fiddle',
        component: RoutedSketchPageComponent,
        data: bezierFiddle,
      },
      {
        path: 'bezier-flow-1',
        component: RoutedSketchPageComponent,
        data: bezierFlow1,
      },
      {
        path: 'bezier-flow-2-interactive',
        component: RoutedSketchPageComponent,
        data: bezierFlow2Interactive,
      },
      {
        path: 'bezier-flow-2-static',
        component: RoutedSketchPageComponent,
        data: bezierFlow2Static,
      },
      {
        path: 'bezier-grid-1',
        component: RoutedSketchPageComponent,
        data: bezierGrid1,
      },
      {
        path: 'bezier-grid-2',
        component: RoutedSketchPageComponent,
        data: bezierGrid2,
      },
      {
        path: 'bezier-grid-3-interactive',
        component: RoutedSketchPageComponent,
        data: bezierGrid3Interactive,
      },
      {
        path: 'bezier-grid-3-static',
        component: RoutedSketchPageComponent,
        data: bezierGrid3Static,
      },
    ],
  },
  {
    path: 'flow-field',
    collectionTitle: 'Flow field',
    children: [
      {
        path: 'flow-field-1',
        component: RoutedSketchPageComponent,
        data: flowFieldSketch1,
      },
    ],
  },
  {
    path: 'hitomezachi-stitch',
    collectionTitle: 'Hitomezachi stitch',
    children: [
      {
        path: 'hito1',
        component: RoutedSketchPageComponent,
        data: hito1,
      },
      {
        path: 'hito2',
        component: RoutedSketchPageComponent,
        data: hito2,
      },
      {
        path: 'hito3',
        component: RoutedSketchPageComponent,
        data: hito3,
      },
      {
        path: 'hito4',
        component: RoutedSketchPageComponent,
        data: hito4,
      },
    ],
  },
  {
    path: 'joy-division',
    collectionTitle: 'Joy division',
    children: [
      {
        path: 'joy-division-1',
        component: RoutedSketchPageComponent,
        data: joyDivision1,
      },
    ],
  },
];
